### ISSUE TITLE
English(coming)

### ISSUE THREAD

**Issue by oleg619** [bybit-exchange/bybit-official-api-docs#1]
Hello. When  will be documentation in English?
 Have a nice day.

**Comment by seantao** [comment]
hi @oleg619 
We have scheduled an update next week. We will inform you here once the english documentation is ready.
Thanks

**Comment by seantao** [comment]
hi @oleg619 
We apologize for the delayed update. Have fun in reading the [documentation in English](https://github.com/bybit-exchange/bybit-official-api-docs/blob/master/en/README.md). ;)
