### ISSUE TITLE
No close

### ISSUE THREAD

**Issue by jamespeccia** [bybit-exchange/bybit-official-api-docs#18]
In order to close an order you must buy or sell the opposite quantity and pay double the fee. Add a close order request to prevent this issue.

**Comment by danielytics** [comment]
The only way to close your position is to do an opposite order. When you hold a long position, the way to close it is to sell your contracts to someone who wishes to buy them. Every trade has a buy and a sell. This is the same on every margin trading exchange. There is no way to close a position without either buying or selling. [Here's a reddit post on the BitMEX subreddit explaining it in more detail.](https://www.reddit.com/r/BitMEX/comments/cr8by2/do_i_understand_the_relationship_between_shorts/)

If you do not wish to pay taker fees, the only option is to try to exit using limits.

**Comment by jamespeccia** [comment]
Is it possible to send post-only requests so I never pay taker fees? If it is not available now, will it ever?

**Comment by dexter-2** [comment]
@jamespeccia Of course! Set the time_in_force param to PostOnly.
