### ISSUE TITLE
拼接顺序按照参数名升序排列

### ISSUE THREAD

**Issue by Aixinwei** [bybit-exchange/bybit-official-api-docs#2]
这个签名的时候没有必要按照字母顺序进行签名吧，写的什么代码，只顾得自己方便了？

**Comment by songhaitao** [comment]
排序是为了确保客户端和服务端加签的字符串是一致的。

**Comment by Aixinwei** [comment]
后台验签直接对传过来的字符串进行签名验证，按顺序排然后再验签不是制造麻烦吗？传参数还要去检查顺序是不是和你们的一致。time_in_force优先级竟然比timestamp高

**Comment by songhaitao** [comment]
不同的服务端语言、客户端语言都有各自的参数封装和解析实现，实现可能不尽相同，
参数排序只是在此之上的一个约定，方便前后端统一。
目前业界大部分开放接口都是这样的设计，还请了解下，谢谢！
