### ISSUE TITLE
How can I authentication usd javascript?

### ISSUE THREAD

**Issue by sangjin0309** [bybit-exchange/bybit-official-api-docs#28]
```
<script>
	var url = 'https://api.bybit.com';
	var api_key = 'myapikey';
	var timestamp = Date.now() + 1000;
	var secret = 'mysecret';

	function leverage() {
		var sub_url = "/user/leverage/save";
		
		var param_str = 'api_key=' + api_key + '&leverage=' + 15 + '&symbol=XRPUSD&timestamp=' + timestamp; 
		var hash = CryptoJS.HmacSHA256(param_str, secret);
		var sign = CryptoJS.enc.Base64.stringify(hash);
		
		var param = '?' + param_str + '&sign=' + sign;

		var f = {
			"api_key": api_key,
			"leverage": 15,
			"symbol": "XRPUSD",
			"timestamp": timestamp,
			"sign": sign
		};
		
		console.log(f);
	
		var xhr = new XMLHttpRequest();
		xhr.open("POST", url + sub_url + param, true);
		xhr.setRequestHeader("Content-Type", "application/json");
		xhr.onreadystatechange = function () {
		    if (xhr.readyState === 4 && xhr.status === 200) {
		        var json = JSON.parse(xhr.responseText);
		        console.log(json);
		    }
		};
	 	var data = JSON.stringify(f);
		xhr.send();
	}

	$(document).ready(function() {
		leverage();
	});
</script>
```

is it same encrypt?

hex(HMAC_SHA256($secret, $param_str));  < it can't use in javascript.

i don't konw how to modify my code please help me

The status is 200, but console.log returns :

{ret_code: 10011, ret_msg: "Origin header invalid.", ext_code: "", result: null, ext_info: null}

Am I totally wrong about the api document?

Is the encryption method wrong? Then how to modify it?

Is there a problem with the transmission method?

**Comment by keyganker** [comment]
1. use `crypto` module to encrypt
2. all params is already is query string, so there is no need to send body
there is a sample:
```
const XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
const crypto = require('crypto');

var url = 'https://api.bybit.com';
var sub_url = "/user/leverage/save";
var api_key = "";
var secret = "";
var timestamp = Date.now()+1000;

var param_str = 'api_key=' + api_key + '&leverage=' + 15 + '&symbol=XRPUSD&timestamp=' + timestamp;
const signature = crypto.createHmac('sha256', secret)
                   .update(param_str)
                   .digest('hex');

var param = '?' + param_str + '&sign=' + signature;
var xhr = new XMLHttpRequest();
xhr.open("POST", url + sub_url + param, true);
xhr.setRequestHeader("Content-Type", "application/json");
xhr.onreadystatechange = function () {
    if (xhr.readyState === 4 && xhr.status === 200) {
        var json = JSON.parse(xhr.responseText);
        console.log(json);
    }
};
	//var data = JSON.stringify(f);
xhr.send();
```

**Comment by alsaidi33** [comment]
> ```
> <script>
> 	var url = 'https://api.bybit.com';
> 	var api_key = 'myapikey';
> 	var timestamp = Date.now() + 1000;
> 	var secret = 'mysecret';
> 
> 	function leverage() {
> 		var sub_url = "/user/leverage/save";
> 		
> 		var param_str = 'api_key=' + api_key + '&leverage=' + 15 + '&symbol=XRPUSD&timestamp=' + timestamp; 
> 		var hash = CryptoJS.HmacSHA256(param_str, secret);
> 		var sign = CryptoJS.enc.Base64.stringify(hash);
> 		
> 		var param = '?' + param_str + '&sign=' + sign;
> 
> 		var f = {
> 			"api_key": api_key,
> 			"leverage": 15,
> 			"symbol": "XRPUSD",
> 			"timestamp": timestamp,
> 			"sign": sign
> 		};
> 		
> 		console.log(f);
> 	
> 		var xhr = new XMLHttpRequest();
> 		xhr.open("POST", url + sub_url + param, true);
> 		xhr.setRequestHeader("Content-Type", "application/json");
> 		xhr.onreadystatechange = function () {
> 		    if (xhr.readyState === 4 && xhr.status === 200) {
> 		        var json = JSON.parse(xhr.responseText);
> 		        console.log(json);
> 		    }
> 		};
> 	 	var data = JSON.stringify(f);
> 		xhr.send();
> 	}
> 
> 	$(document).ready(function() {
> 		leverage();
> 	});
> </script>
> ```
> 
> is it same encrypt?
> 
> hex(HMAC_SHA256($secret, $param_str)); < it can't use in javascript.
> 
> i don't konw how to modify my code please help me
> 
> The status is 200, but console.log returns :
> 
> {ret_code: 10011, ret_msg: "Origin header invalid.", ext_code: "", result: null, ext_info: null}
> 
> Am I totally wrong about the api document?
> 
> Is the encryption method wrong? Then how to modify it?
> 
> Is there a problem with the transmission method?

This only happens with change user leverage and I dont know why
