### ISSUE TITLE
API Klines

### ISSUE THREAD

**Issue by m-root** [bybit-exchange/bybit-official-api-docs#3]
Hello,

Is it possible for me to get Klines on API or WebSockets but more historical candles?

{"op":"subscribe","args":["kline.BTCUSD.1m"]} this gives me one candle stick. I need to regulate the number of candle sticks that I can fetch.

It would also be great if we can fetch the Klines through the API if you don't mind

**Comment by m-root** [comment]
{"op":"subscribe","args":["kline.BTCUSD.1m"]} this gives me one candle stick. I need to regulate the number of candle sticks that I can fetch. 

I do hope that this helps.

**Comment by songhaitao** [comment]
Hi @m-root,

We will add an API that can fetch historical candles. It may be released in two weeks.

Thanks for your advice!

**Comment by m-root** [comment]
Hi **@songhaitao ,**

Thank you for the response. What is the status as of now?

Thanks.

**Comment by songhaitao** [comment]
Sorry about delayed.

There is some high priority work to do. We may schedule it this week and will be released this or next week.

**Comment by m-root** [comment]
Okay. Thank you.

**Comment by songhaitao** [comment]
Hi @m-root ,

We have released this feature now, [Here is the doc](urlhttps://bybit-exchange.github.io/bybit-official-api-docs/en/index.html)

**Comment by m-root** [comment]
Thanks. Let me have a look at it.
