### ISSUE TITLE
Duplicate return codes in bybit errors doc

### ISSUE THREAD

**Issue by karanjitsingh** [bybit-exchange/bybit-official-api-docs#32]
https://github.com/bybit-exchange/bybit-official-api-docs/blob/master/en/errors.md

The error codes `20005` and `20006` have repeated usages

![image](https://user-images.githubusercontent.com/4632805/65372884-a949cc80-dc93-11e9-982d-257ae33bcead.png)

![image](https://user-images.githubusercontent.com/4632805/65372894-bc5c9c80-dc93-11e9-9710-e616a1d9a8bb.png)

![image](https://user-images.githubusercontent.com/4632805/65372901-cb434f00-dc93-11e9-812b-bb90ec8b8e85.png)

![image](https://user-images.githubusercontent.com/4632805/65372906-da2a0180-dc93-11e9-9b74-fbd932b9c166.png)

Is this a doc typo or are these return codes actually duplicated?

**Comment by keyganker** [comment]
Thank you for your feedback!
 is a typo error and it's fixed
