### ISSUE TITLE
Place_order error 10002

### ISSUE THREAD

**Issue by AlexLup** [bybit-exchange/bybit-official-api-docs#40]
Hello,

I am working on a trading bot, in python, using the ByBit api and I got an error during the creation of a new order (Place_order). 

({'ret_code': 10002, 'ret_msg': 'invalid request, please check your timestamp and recv_window param. req_timestamp: 1571603078000 server_timestamp: 1571603076440 recv_window: 5000', 'ext_code': '', 'result': None, 'ext_info': None, 'time_now': '1571603076.434877'}, <bravado.requests_client.RequestsResponseAdapter object at 0x7fc16b9c3f60>)

I do not understand why I got this error since the same code was working always yesterday. I do not know how to solve it.

**Comment by xldistance** [comment]
You got request timeout,may be your network has problem

**Comment by AlexLup** [comment]
I do not understand what was the problem but now it is working fine

**Comment by JoshColeen** [comment]
I've got same problem. Not yet solved. Is it network problem?

**Comment by mark-sch** [comment]
I am facing the same problem, request timestamp is in epoch milliseconds, and it happens on a small amount of requests periodically. It can be considered as a network delay, skipped and retried, correct?
