### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by captholley** [bybit-exchange/bybit-official-api-docs#45]
I am having trouble getting connected to the rest API. I have been successful at connecting to the test net server but when I try to connect to the real-time server I keep getting a 10003 error. This is despite setting up the API key the same way for the live account as I did for the test net. I am using the correct domains, etc. Any ideas what I might be missing?

**Comment by keyganker** [comment]
We need your request detail.
There is a [telegram group](https://t.me/Bybitapi), and you can get feedback in time there

**Comment by captholley** [comment]
Make sure to use the correct domain!
