### ISSUE TITLE
get kline history

### ISSUE THREAD

**Issue by AlexLup** [bybit-exchange/bybit-official-api-docs#56]
Hi all,

I have implemented in python the kline REST end point that was missing in the test.py file. To make it work I had to change the \bravade\client.py because I need a variable named "from" that in python is a key word. 

`    def get_kline(self,sym,interval,from_time,limit="200"):
        tmp = self.client.Kline.Kline_get(symbol=sym,interval=interval,from_time=from_time,limit=limit).result()
        tmp = tmp[0]['result']
        return tmp`

I added this code in the __call__ function to change the variable name

`        if "from_time" in op_kwargs:
            op_kwargs["from"]=op_kwargs.pop("from_time")`

Does someone have a better idea on how to do it without changing the bravado library?

**Comment by SimonZgx** [comment]
There is no better way at the moment. Maybe we will consider modifying the name of the filed later.

**Comment by SimonZgx** [comment]
And I have submitted the BUG to the bravado developer. https://github.com/Yelp/bravado/issues/438

**Comment by SimonZgx** [comment]
```js
kline_get_kwargs = {
    'symbol': 'BTCUSD',
    'interval': '1m',
    'from': '1572231328',
}
client.Kline.Kline_get(**kline_get_kwargs)
```

There is a better solution above.
