### ISSUE TITLE
klineV2 topic 'data' property is capitalized as 'Data'

### ISSUE THREAD

**Issue by whats0n0** [bybit-exchange/bybit-official-api-docs#59]
On the new `klineV2` websocket topic the websocket response has a capitalized property called 'Data', but in all other topics the property is lowercase 'data'.
The documentation also says that it should be lowercase 'data', but that is incorrect.  @dexter-2 
```javascript
{
    'topic': 'klineV2.1.BTCUSD', 
    'data': [{ // This is wrong, the websocket property is 'Data'
        'start': 1572425640, 
        'end': 1572425700,       
        ...
    }],
    'timestamp_e6': 1572425677047994
}
```

**Comment by dexter-2** [comment]
Thanks for the report, we will fix this so that it is inline with the rest of the endpoints.

Appreciate the help.

**Comment by SimonZgx** [comment]
fixed
