### ISSUE TITLE
Placing a market order, I can't figure it out

### ISSUE THREAD

**Issue by palentir** [bybit-exchange/bybit-official-api-docs#64]
Hello, I have successfully got a response from /v2/private/execution/list, so I at least have the main authentication stuff figured out. But I can't seem to place an order. The strange thing is I get error code: -1

Here is the code I am using written in php. Can someone tell me if I've made a mistake here?

`$public_key = 'hidden';`
`$secret_key = 'hidden';`
`$url = 'https://api-testnet.bybit.com/open-api/order/create';`
`$symbol = 'BTCUSD';`
`$time_stamp = time() * 1000;`
`$side = 'Buy';`
`$order_type = 'Market';`
`$qty = 500;`
`$stop_loss = '';`
`$time_in_force = '';`
`$price = '';`

`$params = ['symbol' => $symbol, `
`           'timestamp' => $time_stamp,`
`           'side' => $side, `
`           'order_type' => $order_type, `
`           'qty' => $qty, `
`           'price' => $price, `
`           'time_in_force' => $time_in_force`
`           ];    `

`$response = json_decode(file_get_contents($url . "?" . $this->get_signed_params($public_key, $secret_key, $params)));`

Output: stdClass Object ( [ret_code] => -1 [ret_msg] => [ext_code] => [result] => [ext_info] => [time_now] => 1573142780.458658 )

**Comment by palentir** [comment]
I just got in touch with their support on telegram, who were fantastic!

My issue was I did not read this section properly.

> HTTP Requests  
>  GET requests should be in the application/x-www-form-urlencoded format
>  POST requests should be in the application/json format

So my get_signed_params function remains the same but I just set the params into a json format for those types of api function calls.

**Comment by LiteSaber** [comment]
> I just got in touch with their support on telegram, who were fantastic!
> 
> My issue was I did not read this section properly.
> 
> > HTTP Requests
> > GET requests should be in the application/x-www-form-urlencoded format
> > POST requests should be in the application/json format
> 
> I made a new version of get_signed_params, called post_signed_params. I replaced it with a curl function that can send and receive json, using many elements from the get_signed_params function. Had a little issue with a trailing 1, after a google, I found out an addition curl parameter to avoid that. Now it all works perfectly. Just make a note of the type of HTTP request you are calling and call the corresponding function.

Any chance you can share your completed code for this? I'm having issues as well. I can get it to give back a list of trade history, but when trying to actually create/open a trade it does nothing.
