### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by axelkrumbach** [bybit-exchange/bybit-official-api-docs#9]
Hello, i got {"ret_code":10004,"ret_msg":"error sign!","ext_code":"","result":null,"ext_info":null,"time_now":"1560094053.519714","rate_limit_status":799}
Wehen sending https://api.bybit.com/open-api/order/list?api_key=1OGDohRQys8PuCLgEl&timestamp=1560093891337&sign=37363534326630373436373066343333613263373734666362643964303538663863633630393239316537346431623432313165303361623937353830343933
is there a list where error codes are explained?

**Comment by songhaitao** [comment]
We will still add the error description.
